- dist/hass-aarlo.js
- install
Move JS tidy up into master branch. Fixes include:
* proper litelement use
* better event handling
* less traffic and image collecting
* better lifecycle
* better function and variable naming
> Js tidy up

- changelog
- dist/hass-aarlo.js
Reduced number of renders happening.
> 0.0.5 Speed up

- changelog
- dist/hass-aarlo.js
Better battery and charger status handing.
> 0.0.6: Battery and charger statuses

- changelog
- dist/hass-aarlo.js
Testing some image updating logging, I'm trying to find the best way to update an image change.
> image update logging

- .gitignore
- changelog
- custom_cards.json
- dist/hass-aarlo.js
Code now checks for a mobile browser and treats the video component differently.
> 0.0.7 check for mobile browser

- .gitignore
- dist/hass-aarlo.js
Fix up video controls for stream and library playback.
> merge custom controls

- .gitignore
- changelog
- custom_cards.json
- dist/hass-aarlo.js
> v0.0.8; merge in custom controls 

- README.md
- dist/hass-aarlo.js
Allow a light to be associated with a camera.
> Light control

- changelog
- custom_cards.json
- dist/hass-aarlo.js
Remove `camera_thumbnail` web service call to handle https://github.com/home-assistant/core/pull/32473
> removed camera_thumbnail

- README.md
- changelog
- custom_cards.json
- dist/hass-aarlo.js
Added support for custom device IDs for motion, sound, battery devices.
> Custom ids

- changelog
- custom_cards.json
- dist/hass-aarlo.js
Added a missing image update after camera source changes.
> Missing update

- changelog
- custom_cards.json
- dist/hass-aarlo.js
> Used v3.1.1 of mpeg-dash.

- changelog
- custom_cards.json
- dist/hass-aarlo.js
Initial test for square aspect ratio.
> Experimental square aspect ratio support.

- dist/hass-aarlo.js
A complete re-write of the class. Initial check in, includes but not limited to:
- UI operates programmatically; the old code would change the UI by resubmitting the HTML piece, the new code modifies the document from the javascript; a lot more efficient
- Library is dynamic, if a capture happens the library will reload
- Uses Arlo directly where possible, for thumnbails and so on
- Better naming and flow internally
> v0.2 initial pull request

- dist/hass-aarlo.js
- lang/en.js
- lang/en2.js
- lang/fs.js
Added ability to change language of cards.
> Localisation Support

- dist/hass-aarlo.js
Improve startup flow.
Improve update recognition.
Allow snapshot timeouts to be changed.
Remove `replaceAll()` dependency.
> Library improvements

- dist/hass-aarlo.js
Many fixes:
- remove strings from html render, they are all added by programatically
- load language pack then render display
- language is card specific
> Language tidy up.

- dist/hass-aarlo.js
- lang/en.js
- lang/fr.js
Fix library change issues. Better start up.
> Library Tidy Up

- dist/hass-aarlo.js
Much tidy to more explicity track library changes.
> Empty library

- lang/de.js.html
German localization - have to check in the UI if its sensible once it is merged and released...
> German language file

- README.md
- dist/hass-aarlo.js
In light of all the new options I'm re-working the configuration.
> New configuration.

- dist/hass-aarlo.js
When I added the new config I broke the old play direct and auto play functionality.
> Add direct and autoplay back for old config.

- dist/hass-aarlo.js
Fix issues on iPhones and iPads.
Made flow of setup/teardown a lot nicer.
Added initial alerts.
Better naming of video/recording.
Startup on iPad looking better.
> Stream tidy up

- README.md
- dist/hass-aarlo.js
Coalesced recording-player and stream-player into video-player.
Tidied some method names.
Added `muted` option.
> Recordings and Streaming.

- dist/hass-aarlo.js
- lang/de.js
- lang/en.js
- lang/es.js
- lang/fr.js
- lang/it.js
- lang/sv.js
Add camera state to language pack.
> Add camera state to language pack.

- README.md
- dist/hass-aarlo.js
Finalised location of global/per-camera pieces.
> Tidy Config.

- README.md
- dist/hass-aarlo.js
- lang/de.js
- lang/en.js
- lang/es.js
- lang/fr.js
- lang/it.js
- lang/sv.js
> Add duration option.

- README.md
- dist/hass-aarlo.js
Also hide left/right for different cameras on mobile screens.
> Small and tiny icon and font sizes.

- lang/pt-BR.js
Add brazilian portuguese translation
> Add brazilian portuguese translation

- README.md
- changelog
- dist/hass-aarlo.js
- info.md
- install
Big changes...
moved to HTML element
do everything programmatically
add lock/light into stream player
removed old config support
> version 0.3
